### ISSUE TITLE
Bug in CubicSplines.jl line 38, with fix

### ISSUE THREAD

**Issue by PGS62** [sp94/CubicSplines.jl#3]
I discovered that the interpolated values given from CubicSplines.jl do not match those given by the R function [`aspline`](https://www.rdocumentation.org/packages/akima/versions/0.6-2/topics/aspline) for input values in the interval `xs[end-1]` to `xs[end]`

It's not too hard to use a symmetry argument to see that the Julia splined value must be wrong, as set out in the script below. I believe the fix is at line 38 of CubicSplines.jl which should read:
`for i in 1:length(ms)`
rather than
`for i in 1:length(ms)-1`

```
using CubicSplines
using RCall
using Plots

#=CubicSplines2.jl is a copy of CubicSplines.jl with line 38 changed from:
for i in 1:length(ms)-1
to read instead:
for i in 1:length(ms)
=#
include("CubicSplines2.jl")

xs = collect(-2.0:2.0)
ys = mod.(xs, 2)
xin = collect(-2.0:0.5:2.0)

#=By symmetry about zero we should have result(+x) = result(-x)
But that's not true when x is in the interval xs[end-1] to xs[end]

CubicSplines.CubicSpline(xs, ys)[ 1.5] == 0.725
CubicSplines.CubicSpline(xs, ys)[-1.5] == 0.75

As a further check, compare against R's aspline https://www.rdocumentation.org/packages/akima/versions/0.6-2/topics/aspline
=#

j_res = CubicSplines.CubicSpline(xs, ys)[xin]
J_res = CubicSplines2.CubicSpline(xs, ys)[xin]
R_res = rcopy(rcall(:aspline, xs, ys, xin))[:y]

@show xin
@show j_res
@show J_res
@show R_res

@show all(j_res .== R_res)
@show all(J_res .== R_res)

plot(xin,j_res)
plot!(xin,R_res)
```

running that script:

```
xin = [-2.0, -1.5, -1.0, -0.5, 0.0, 0.5, 1.0, 1.5, 2.0]
j_res = [0.0, 0.75, 1.0, 0.5, 0.0, 0.5, 1.0, 0.725, 0.0]
J_res = [0.0, 0.75, 1.0, 0.5, 0.0, 0.5, 1.0, 0.75, 0.0]
R_res = [0.0, 0.75, 1.0, 0.5, 0.0, 0.5, 1.0, 0.75, 0.0]
all(j_res .== R_res) = false
all(J_res .== R_res) = true
```

**Comment by sp94** [comment]
Thanks Philip, looks like you're absolutely right. Sorry if this has caused you any problems.

I'll push the change and add your symmetry test tonight.

**Comment by PGS62** [comment]
You're welcome. A lot of my coding these days is porting code I've written in recent years in R over to Julia so that's how I realised there was a bug. Your code was very clear so finding the bug was straightforward.

**Comment by sp94** [comment]
Fixed in https://github.com/sp94/CubicSplines.jl/releases/tag/v0.1.1 

You should be able to update through the Julia package manager. Thanks for sharing!
