### ISSUE TITLE
Documentation of extrapolation

### ISSUE THREAD

**Issue by sp94** [sp94/CubicSplines.jl#6]
@StefanMathis thanks very much for your pull request #5. I have a couple questions about some of the documentation

### In `CubicSplines.jl`

> The extrapolation behaviour is defined by the coefficients of a 3rd degree
> polynomial which can be given as additional keyword arguments extrapl and extrapr
> to the constructor. extrapl and/or extrapr should be either "nothing" or a
> set of coefficients.
> 
> Case 1: Extrapolation is set to "nothing"
> In this case, the default quadratic extrapolation according to section 2.3 of [1]
> is used to construct the spline and the spline throws an error when evaluated
> outside its boundaries.
> 
> Case 2: Extrapolation is set to a vector
> The container is given as a n-element collection of values:
>     extrapl = [p1, p2, p3, ..., pn]
> which are used to evaluate the following function:
>     y = p0 + p1*(x-x3) + p2*(x-x3)^2 + p3*(x-x3)^3 + ... + pn*(x-x3)^n
> The constant p0 is equal to y3 by definition (continuous spline). x3 and y3
> are the first/last datapoint values respectively.

Does the first paragraph contradict the third paragraph? Should we remove "3rd degree" from the first line?

---

### In `README.md`

The example doesn't run (it doesn't include the xdata and ydata). Do you know what xdata and ydata were used?

**Comment by StefanMathis** [comment]
Hey, good catch, I was apparently a little bit sloppy when writing the docs. You are of course right, the extrapolation polynomials can have an arbitrary degree.
Regarding the example in the README: This is taken straight from runtests.jl. The xdata and ydata is as follows:

```julia
# Interpolate a sine function with white noise
xdata = range(0,stop=4π,length=20) .+ 0.5*rand(MersenneTwister(1234),20)
ydata = sin.(xdata)
```

Should I issue a new pull request or could you insert this code snippet at the start (behind the `using ...`?

**Comment by sp94** [comment]
Hi Stefan,

I rewrote a more minimal example for the extrapolation - could you take a look and check I understood what's happening correctly? If it looks OK to you I'll close this issue

Thanks again for sharing your contribution!

**Comment by StefanMathis** [comment]
Hello Samuel,

this is excellent and much more understandable than the lengthy code snippet I gave. From my point of view, we can leave it like this.

The only suggestion I have is that we could leave a small hint regarding the default values of `extrapl` and `extrapr` and that they can be defined independently. Perhaps something like this:

> The two polynomials can be defined independently of each other. It is also possible to just extrapolate to the left by only giving coefficients for `extrapl`. `extrapr` is then set to the default value `nothing`, which leads to the extrapolation error illustrated above when requesting values to the right of the spline. 

What do you think?

**Comment by sp94** [comment]
Added, thanks!
