### ISSUE TITLE
Suggestion: remove restriction on real numbers

### ISSUE THREAD

**Issue by StefanMathis** [sp94/CubicSplines.jl#8]
Hello,

I'm currently using `CubicSplines.jl` together with the `Unitful.jl` package. Since the `CubicSpline` struct is currently restricted to vectors with real elements, this forces me to convert units to real numbers and back. Could we possibly remove the restriction to real elements (instead restricting it to numbers)?

**Comment by StefanMathis** [comment]
I took a look into the matter and I found that there is more to do than simply allowing for number input. The real problem is the spline coefficient matrix `ps`, which cannot be represented by a single unit. Since `Unitful` arrays can only be efficient (read: zero runtime overhead) when all elements have the same time, this would mean splitting the coefficient matrix into four vectors (one for each dimension). This would lead to some loss in elegance (but not efficiency!), however the gain would be a nice interoperability with `Unitful`. As an example, the dependency `B(H)` of ferromagnetic material could be directly represented by a CubicSpline w/o any boilerplate code for unit stripping and then reattaching needed. Once I have a running prototype, I will link it here for reviewing.

**Comment by StefanMathis** [comment]
Okay, I thin I ran into a roadblock. The problem is that there is no good way to deal with the coefficients of the extrapolation vector, since they can't be represented by a single unit (in fact, for each exponent 1, 2, 3, ... a specific unit is needed).

Therefore, I think that a wrapper which removes and re-adds the units around `CubicSplines` is more sensible in such an application. I therefore close this issue.

**Comment by sp94** [comment]
Thanks for looking into this and sharing your findings, Stefan
